blank_issues_enabled: false
contact_links:
  - name: Support question?
    url: https://github.com/ericsizemore/simple_counter/discussions/categories/q-a
    about: If you have any questions about configuring or using Simple Counter, please open a new Q&A discussion.